import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vite';

const patternsFile = fileURLToPath(new URL('./patterns.json', import.meta.url));

// patterns.json lives at the repo root (it is regenerated by the deep research workflow),
// so it is served in dev and emitted into the build output from there.
function patternsPlugin() {
  return {
    name: 'gh-aw-wizard:patterns-json',
    configureServer(server) {
      server.middlewares.use('/patterns.json', (_req, res) => {
        res.setHeader('Content-Type', 'application/json');
        res.end(readFileSync(patternsFile));
      });
    },
    generateBundle() {
      this.emitFile({
        type: 'asset',
        fileName: 'patterns.json',
        source: readFileSync(patternsFile, 'utf8')
      });
    }
  };
}

export default defineConfig({
  root: 'src',
  base: './',
  publicDir: false,
  plugins: [patternsPlugin()],
  build: {
    outDir: '../dist',
    emptyOutDir: true
  }
});
