import { readFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, posix } from 'node:path';
import { defineConfig } from 'vite';

const patternsDir = fileURLToPath(new URL('./patterns', import.meta.url));

// patterns/ lives at the repo root (it is regenerated by the deep research
// workflow) as one manifest plus one file per archetype, so its contents are
// served in dev and emitted into the build output from there.
function listPatternsFiles() {
  const archetypeFiles = readdirSync(join(patternsDir, 'archetypes'))
    .filter((name) => name.endsWith('.json'))
    .map((name) => posix.join('archetypes', name));
  return ['manifest.json', ...archetypeFiles];
}

function patternsPlugin() {
  return {
    name: 'gh-aw-wizard:patterns-json',
    configureServer(server) {
      const files = listPatternsFiles();
      server.middlewares.use('/patterns/', (req, res, next) => {
        const relativePath = decodeURIComponent(req.url.replace(/^\/+/, '').split('?')[0]);
        if (!files.includes(relativePath)) {
          next();
          return;
        }
        res.setHeader('Content-Type', 'application/json');
        res.end(readFileSync(join(patternsDir, ...relativePath.split('/'))));
      });
    },
    generateBundle() {
      listPatternsFiles().forEach((relativePath) => {
        this.emitFile({
          type: 'asset',
          fileName: posix.join('patterns', relativePath),
          source: readFileSync(join(patternsDir, ...relativePath.split('/')), 'utf8')
        });
      });
    }
  };
}

export default defineConfig({
  root: 'src',
  base: './',
  publicDir: false,
  plugins: [patternsPlugin()],
  build: {
    outDir: '../dist',
    emptyOutDir: true
  }
});
