name: "Copilot Setup Steps"
on: workflow_call

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install gh-aw extension
        uses: github/gh-aw-actions/setup-cli@v0.87.0
        with:
          version: v0.87.0
